spring:
  application:
    name: prescription-analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/prescriptiondb
    username: rxadmin
    password: rxpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        options:
          temperature: 0.0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

google:
  cloud:
    vision:
      credentials-path: classpath:google-vision-credentials.json

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.3-70b-versatile

server:
  port: 8080
